name: Metrics

on:
  # Schedule updates (each hour)
  # schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  # push: {branches: ["metrics"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          repositories_forks: no
          
          plugin_introduction: yes
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year
          
          plugin_languages: yes
          
          plugin_followup: yes
          
          plugin_people: yes
          plugin_people_types: followers, following
          
          plugin_stargazers: yes
          
          plugin_activity: yes
          plugin_activity_limit: 10           # Limit to 5 events
          
          plugin_achievements: yes
          
          plugin_notable: yes
          
          plugin_discussions: yes
          
          plugin_lines: yes
          
          plugin_repositories: yes
          
          plugin_gists: yes
          
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_limit: 5
